name: debe-to-kindle-push

on: [push]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  debe-to-kindle-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run debe-to-kindle-push
        run: python main.py
      - name: create env var for date
        run: |
          echo "DATE=$(python -c 'from datetime import date; print(date.today())')" >> $GITHUB_ENV
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: SalihEREN
          password: SefuroksimA
          subject: debe - ${{env.DATE}}
          to: saliheren@hotmail.co.uk
          from: saliheren@hotmail.co.uk
          ignore_cert: true
          secure: true
          html_body: README.md
          attachments: Eksisozluk DEBE - ${{env.DATE}}.html
